services:
  backend:
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/package.json

  frontend:
    env_file:
      - ./frontend/.env
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/package.json

  pgadmin:
    env_file: "./backend/.env"
    container_name: pgadmin_3
    image: dpage/pgadmin4:8.9
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - pgadmin_data:/var/lib/pgadmin/
    depends_on:
      - postgres

volumes:
  pgadmin_data:
