services:
  postgres:
    env_file: "./backend/.env"
    container_name: postgres_2
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  pgadmin:
    env_file: "./backend/.env"
    container_name: pgadmin_2
    image: dpage/pgadmin4:8.9
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - pgadmin_data:/var/lib/pgadmin/
    depends_on:
      - postgres

volumes:
  postgresql_data:
  pgadmin_data:
