import express from "express";
import userRouter from "./users";
import productRouter from "./products";
import authRouter from "./auth";
import orderRouter from "./orders";
import categoryRouter from "./categories";
import discountRouter from "./discount";
import userProductRouter from "./reviews";
const router = express();
router.use("/users", userRouter);
router.use("/reviews", userProductRouter);
router.use("/products", productRouter);
router.use("/orders", orderRouter);
router.use("/auth", authRouter);
router.use("/categories", categoryRouter);
router.use("/discount", discountRouter);
export default router;
