import express from "express";
import userRouter from "./users";
import productRouter from "./products";
import authRouter from "./auth";
import orderRouter from "./orders";
const router = express();
router.use("/users", userRouter);
router.use("/products", productRouter);
router.use("/orders", orderRouter);
router.use("/orders", authRouter);
export default router;
