import { PERMISSION, ROLE } from "@prisma/client";

export const permissions = {
  [ROLE.SUPER_ADMIN]: [
    PERMISSION.SUPER_ADMIN_GET,
    PERMISSION.SUPER_ADMIN_POST,
    PERMISSION.SUPER_ADMIN_DELETE,
    PERMISSION.SUPER_ADMIN_PUT,
    PERMISSION.ADMIN_GET,
    PERMISSION.ADMIN_POST,
    PERMISSION.ADMIN_DELETE,
    PERMISSION.ADMIN_PUT,
    PERMISSION.USER_GET,
    PERMISSION.USER_POST,
    PERMISSION.USER_DELETE,
    PERMISSION.USER_PUT,
    PERMISSION.REPORT_GET,
  ],
  [ROLE.ADMIN]: [
    PERMISSION.ADMIN_GET,
    PERMISSION.ADMIN_POST,
    PERMISSION.ADMIN_DELETE,
    PERMISSION.ADMIN_PUT,
    PERMISSION.USER_GET,
    PERMISSION.USER_POST,
    PERMISSION.USER_DELETE,
    PERMISSION.USER_PUT,
  ],
  [ROLE.USER]: [
    PERMISSION.USER_GET,
    PERMISSION.USER_POST,
    PERMISSION.USER_DELETE,
    PERMISSION.USER_PUT,
  ],
};
